theme = "tokyonight_storm_transparent"

[editor]
bufferline = "multiple"
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

