# tasks to complete before running roles
- hosts: localhost
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: update Arch package cache
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: update Debian-based package cache
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

# run roles by ansible_hostname

- hosts: localhost
  connection: local
  tags: always,base
  become: true
  tasks:
    - include_tasks: roles/base/tasks/main.yml

- hosts: localhost
  connection: local
  tags: workstation
  become: true
  tasks:
    - include_tasks: roles/workstation/tasks/main.yml
      when: ansible_hostname in ["ArchDesktop", "ArchLaptop", "Archtestmachine"]

- hosts: localhost
  connection: local
  tags: workstation
  become: true
  tasks:
    - include_tasks: roles/workstation/tasks/second-pass.yml
      when: ansible_hostname in ["ArchDesktop", "ArchLaptop", "Archtestmachine"]

- hosts: localhost
  connection: local
  tags: file_server
  become: true
  tasks:
    - include_tasks: roles/file_server/tasks/main.yml
      when: ansible_hostname in ["ubuntu-server"]
  



