- name: users | jem | create personal config directories
  tags: jem,settings,users,dotfiles
  file:
    path: /home/jem/{{ item.dir }}
    state: directory
    owner: jem
    group: jem
    mode: 0700
  with_items:
    - {dir: .config }
    - {dir: .config/alacritty }
    - {dir: .config/fish }
    - {dir: .config/helix }
    - {dir: .config/qtile }
    - {dir: .config/qutebrowser }
    - {dir: .config/zsh }
    - {dir: .config/lvim }
    - {dir: .keychain }
    - {dir: documents }
    - {dir: documents/ISOs }
    - {dir: downloads }
    - {dir: repos }
    - {dir: VMs }
    - {dir: wallpapers }
    - {dir: wallpapers/wallpapers }

- name: users | jem | check if old user folders exist
  stat:
    path: /home/jem/Documents/
  register: old_folders

- name: users | jem | move files to new user folders
  tags: jem,settings,users,dotfiles
  synchronize:
    owner: true
    src: /home/jem/{{ item.src }}
    dest: /home/jem/{{ item.dest }}
  with_items:
    - { src: 'Documents', dest: 'documents' }
    - { src: 'Downloads', dest: 'downloads' }
  when: old_folders.stat.exists
  ignore_errors: true

- name: users | jem | remove unwanted stuff from home directory
  file:
    path: /home/jem/{{ item }}
    state: absent
  with_items:
    - Public
    - Templates
    - Desktop
    - Documents
    - Downloads
    - Music
    - Videos

- name: users | jem | copy personal config files
  tags: jem,dotfiles,users
  copy:
    src: files/{{ item.src }}
    dest: /home/jem/{{ item.dest }}
    owner: jem
    group: jem
    mode: 0600
  with_items: 
    - { src: 'wallpapers', dest: 'wallpapers/' }
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'zshrc', dest: '.config/zsh/.zshrc' }
    - { src: 'xprofile', dest: '.xprofile' }
    - { src: 'starship.toml', dest: '.config/starship.toml' }
    - { src: 'fish/config.fish', dest: '.config/fish/config.fish' }

- name: users | jem | copy triple monitor config
  tags: jem,dotfiles,users
  copy:
    src: files/{{ item.src }}
    dest: /etc/X11/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items: 
    - { src: 'xorg.conf', dest: 'xorg.conf' }
  when: ansible_hostname == "ArchDesktop"
