- name: users | jem | remove unwanted stuff from home directory
  file:
    path: /home/jem/{{ item }}
    state: absent
  with_items:
    - Public
    - Templates

- name: users | jem | create personal config directories
  tags: jem,settings,users,dotfiles
  file:
    path: /home/jem/{{ item.dir }}
    state: directory
    owner: jem
    group: jem
    mode: 0700
  with_items:
    - {dir: .config }
    - {dir: .config/alacritty }
    - {dir: .config/qtile }
    - {dir: .config/lvim }
    - {dir: .keychain }
    - {dir: documents }
    - {dir: documents/ISOs }
    - {dir: downloads }
    - {dir: VMs }
    - {dir: wallpapers }
    - {dir: wallpapers/wallpapers }

- name: users | jem | move Documents to documents
  tags: jem,settings,users,dotfiles
  synchronize:
    owner: true
    src: /home/jem/{{ item.src }}
    dest: /home/jem/{{ item.dest }}
  with_items:
    - { src: 'Documents', dest: 'documents/' }
    - { src: 'Downloads', dest: 'downloads/' }

- name: users | jem | copy personal config files
  tags: jem,dotfiles,users
  copy:
    src: files/{{ item.src }}
    dest: /home/jem/{{ item.dest }}
    owner: jem
    group: jem
    mode: 0600
  with_items: 
    - { src: 'wallpapers', dest: 'wallpapers/wallpapers/' }
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'xprofile', dest: '.xprofile' }

- name: users | jem | copy triple monitor config
  tags: jem,dotfiles,users
  copy:
    src: files/{{ item.src }}
    dest: /etc/X11/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items: 
    - { src: 'xorg.conf', dest: 'xorg.conf' }
  when: ansible_hostname == "ArchDesktop"
