## Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/jem.yml

  ## install software
  - import_tasks: software/basics.yml
  - import_tasks: software/sddm.yml
  - import_tasks: software/hack-nerd-font.yml
  - import_tasks: software/install-alacritty.yml
  - import_tasks: software/qtile.yml
  - import_tasks: software/qutebrowser.yml
