## Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/jem.yml

  ## install software
  - import_tasks: software/feh.yml
  - import_tasks: software/vim.yml
