# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/jem.yml

## install software
- import_tasks: software/alacritty.yml
- import_tasks: software/chromium.yml
- import_tasks: software/firefox.yml
