#
# ~/.bashrc


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias ls='ls --color=auto'
alias ls='exa'
PS1='[\u@\h \W]\$ '
export PATH="/home/jem/.local/bin:$PATH"
export PATH="$PATH:/home/jem/.cargo/bin"
eval $(keychain --eval --quiet id_ed25519 id_rsa ~/.ssh/LocalKey)

shopt -s histappend
PROMPT_COMMAND="history -n; history -a"
unset HISTFILESIZE
HISTSIZE=2000

function hg() {
  history | rg "$1";
}

function getlines {
  git ls-files | grep "$1" | xargs wc -l;
}

function ansiblelog {
  sudo cat /home/rosie/.ansible/ansible.log
}

# THIS MUST BE AT TEH END OF HTE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "#HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
