format = """
$directory\
$character"""

right_format = """$all"""


[line_break]
disabled = true

[python]
symbol = "󰌠 "
format = '[$symbol($version) ]($style)'

[rust]
format = '[$symbol($version) ]($style)'

[aws]
format = '[$symbol($version) ]($style)'

[bun]
format = '[$symbol($version) ]($style)'

[c]
format = '[$symbol($version) ]($style)'

[cmake]
format = '[$symbol($version) ]($style)'

[cmd_duration]
format = '[⏱ $duration]($style)'

[cobol]
format = '[$symbol($version) ]($style)'

[crystal]
format = '[$symbol($version) ]($style)'

[daml]
format = '[$symbol($version) ]($style)'

[dart]
format = '[$symbol($version) ]($style)'

[deno]
format = '[$symbol($version) ]($style)'

[elixir]
format = '[$symbol($version) ]($style)'

[elm]
format = '[$symbol($version) ]($style)'

[erlang]
format = '[$symbol($version) ]($style)'

[fennel]
format = '[$symbol($version) ]($style)'

[golang]
format = '[$symbol($version) ]($style)'

[gradle]
format = '[$symbol($version) ]($style)'

[haskell]
format = '[$symbol($version) ]($style)'

[haxe]
format = '[$symbol($version) ]($style)'

[helm]
format = '[$symbol($version) ]($style)'

[java]
format = '[$symbol($version) ]($style)'

[julia]
format = '[$symbol($version) ]($style)'

[kotlin]
format = '[$symbol($version) ]($style)'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style)'

[lua]
format = '[$symbol($version) ]($style)'

[nim]
format = '[$symbol($version) ]($style)'

[nodejs]
format = '[$symbol($version) ]($style)'

[ocaml]
format = '[$symbol($version) ]($style)'

[opa]
format = '[$symbol($version) ]($style)'

[perl]
format = '[$symbol($version) ]($style)'

[php]
format = '[$symbol($version) ]($style)'

[purescript]
format = '[$symbol($version) ]($style)'

[red]
format = '[$symbol($version) ]($style)'

[ruby]
format = '[$symbol($version) ]($style)'

[scala]
format = '[$symbol($version) ]($style)'

[swift]
format = '[$symbol($version) ]($style)'

[vagrant]
format = '[$symbol($version) ]($style)'

[vlang]
format = '[$symbol($version) ]($style)'

[zig]
format = '[$symbol($version) ]($style)'

[solidity]
format = '[$symbol($version) ]($style)'
 
