# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=3000
setopt autocd extendedglob nomatch notify share_history
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jem/.config/zsh/.zshrc'

# End of lines added by compinstall
autoload -U colors && colors

# auto/tab complete
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)	

alias cat='bat'
alias ls='exa'
alias tree='exa  --tree' $argv

function hg {
  history | rg "$1";
}

function getlines {
  git ls-files | rg "$1" | xargs wc -l;
}

function ansiblelog {
  sudo cat /home/rosie/.ansible/ansible.log
}

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(starship init zsh)"
