amd_microcode_package: amd-ucode
ansible_cron_minute: "*/5"
cups_package: cups
cron_package: cronie
font_hack_ttf_package: ttf-hack
jem_user_group: users
network_manager_package: networkmanager
openssh_package: openssh
openssh_service: sshd
python_package: python
sddm_package: sddm
sudo_group: wheel
virtualbox_package: virtualbox
wireless_tools_package: wireless_tools
wpa_supplicant_package: wpa_supplicant
