- name: software | all basic workstation-packages
  tags: packages,workstation-packages
  package:
    name: 
      - chromium
      - cups
      - discord
      - feh
      - firefox
      - gawk
      - gimp
      - keychain
      - man-db
      - neovim
      - obs-studio
      - pcmanfm
      - reflector
      - traceroute
      - unclutter
      - vim
    state: latest
  when:
    - ansible_distribution == "Archlinux"
