- name: software | all basic workstation-packages
  tags: packages,workstation-packages
  package:
    name: 
      - chromium
      - cups
      - discord
      - feh
      - firefox
      - gawk
      - gimp
      - keychain
      - man-db
      - make
      - mpv
      - neovim
      - nodejs
      - npm
      - obs-studio
      - pcmanfm
      - pipewire
      - python
      - python-pip
      - qutebrowser
      - reflector
      - rust
      - tar
      - traceroute
      - unclutter
      - vim
    state: latest
  when:
    - ansible_distribution == "Archlinux"
