- name: software | all basic workstation-packages
  tags: packages,workstation-packages
  package:
    name: 
      - chromium
      - cups
      - discord
      - feh
      - firefox
      - gawk
      - gimp
      - keychain
      - man-db
      - make
      - mpv
      - neovim
      - nodejs
      - npm
      - obs-studio
      - pcmanfm
      - pipewire
      - python
      - python-pip
      - qutebrowser
      - reflector
      - rust
      - tar
      - traceroute
      - unclutter
      - vim
      - yt-dlp
    state: latest
  when:
    - ansible_distribution == "Archlinux"

# - name: software | install paru AUR helper
#   tages: packages,workstation-packages,AUR
#   shell: |
#     cd /home/jem
#     sudo pacman -S --needed base-devel
#     git clone https://aur.archlinux.org/paru.git
#     cd paru
#     makepkg -si
#   when:
#     - ansible_distribution == "Archlinux"
