- name: software | all basic workstation-packages
  tags: packages,workstation-packages
  package:
    name: 
      - bat
      - chromium
      - cups
      - discord
      - feh
      - firefox
      - gawk
      - gimp
      - keychain
      - man-db
      - make
      - mpv
      - neovim
      - nodejs
      - noto-fonts-emoji
      - npm
      - obs-studio
      - pcmanfm
      - picom
      - pipewire
      - python
      - python-pip
      - qutebrowser
      - qt5
      - reflector
      - rust
      - starship
      - tar
      - tcpdump
      - traceroute
      - unclutter
      - unzip
      - vim
      - yt-dlp
      - zip
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: latest
  when:
    - ansible_distribution == "Archlinux"

