- name: software | all basic workstation-packages
  tags: packages,workstation-packages
  package:
    name: 
      - chromium
      - cups
      - discord
      - feh
      - firefox
      - gawk
      - gimp
      - keychain
      - man-db
      - make
      - mpv
      - neovim
      - nodejs
      - npm
      - obs-studio
      - pcmanfm
      - pipewire
      - python
      - python-pip
      - qutebrowser
      - reflector
      - rust
      - tar
      - traceroute
      - unclutter
      - vim
      - yt-dlp
    state: latest
  when:
    - ansible_distribution == "Archlinux"

- name: software | install kewlfft aur
  tags: packages,workstation-packages,kewlfft,aur
  shell: | 
    ansible-galaxy collection install kewlfft.aur
  become: yes
  become_user: rosie

- name: software | install paru
  become: false
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
  when:
    - ansible_distribution == "Archlinux"
