- name: software | chromium
  tags: packages,chromium,workstation-packages
  package:
    name: chromium
    state: latest
  when:
    - ansible_distribution == "Archlinux"
    - chromium is defined
    - chromium == true
