- name: software | kitty
  tags: packages,workstation-packages,kitty
  package:
    name: kitty
    state: latest
  when:
    - ansible_distribution == "Archlinux"

- name: software | kitty | dotfile
  tags: workstation-packages,kitty,workstation-packages
  copy:
    src: files/kitty/{{ item.src }}
    dest: /home/jem/.config/kitty/{{ item.dest }}
    owner: jem
    group: jem
    mode: 0600
  with_items:
    - { src: 'kitty.conf', dest: 'kitty.conf' }
    - { src: 'current-theme.conf', dest: 'current-theme.conf' }
  when:
    - ansible_distribution == "Archlinux"


