- name: software | install kewlfft aur
  tags: packages,workstation-packages,kewlfft,aur
  shell: | 
    ansible-galaxy collection install kewlfft.aur
  become: yes
  become_user: rosie
  when:
    - ansible_distribution == "Archlinux"

