- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - "{{ cron_package }}"
    state: latest

- name: system setup | cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

- name: system setup | at | one time run on first install
  tags: at
  shell: /usr/bin/ansible-pull -o -U https://github.com/jkoshiel/home-site-maintenance.git > /dev/null | at now + 2 minutes
  become_user: rosie
  become: true
  when: not kewlfft_installed.stat.exists

- name: system setup | end play if kewlfft was not installed
  meta: end_host
  when: not kewlfft_installed.stat.exists

