- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - "{{ cron_package }}"
    state: latest

- name: system setup | cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

- name: system setup | at | one time run on first install
  tags: at
  become_user: rosie
  become: true 
  command: /usr/bin/ansible-pull -o -U https://github.com/rawToast21/home-site-maintenance.git > /dev/null | at now + 2 minute
  when: not kewlfft_installed.stat.exists

- name: system setup | end play if kewlfft was not installed
  meta: end_play
  when: not kewlfft_installed.stat.exists

- name: system setup | cron | schedule automatic ansible provisioning
  tags: cron
  cron:
    name: "ansible provision"
    user: rosie
    hour: "{{ ansible_cron_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: "/usr/bin/ansible-pull -o -U https://github.com/rawToast21/home-site-maintenance.git > /dev/null"

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  cron:
    name: "ansible refresh at boot"
    user: rosie
    special_time: reboot
    job: "/bin/rm -rf /home/rosie/.ansible/pull"
